/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import tableModel.TableModelKupac;
import controller.Controller;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import domain.Kupac;
import domain.Mesto;
import domain.TipKupca;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.table.TableColumn;
import validator.Validator;

/**
 *
 * @author Saki
 */
public class KreirajKupcaForma extends javax.swing.JFrame {

    private Kupac kupacChange;
    private Kupac kupacCreate;
    private UpravljajKupcimaForma pkf;
    private ArrayList<Kupac> listaKupaca;

    public JComboBox<Mesto> getComboBoxMesto() {
        return comboBoxMesto;
    }

    public void setComboBoxMesto(JComboBox<Mesto> comboBoxMesto) {
        this.comboBoxMesto = comboBoxMesto;
    }

    /**
     * Creates new form KreirajKupcaForma
     */
    public KreirajKupcaForma(JFrame parent, Kupac k) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);
        inicijalizujPolja();
        if (k != null) {
            setTitle("Promeni kupca");
            kupacChange = k;
            pkf = (UpravljajKupcimaForma) parent;
            popuniIzmenuKupac(kupacChange);
        }
    }

    public KreirajKupcaForma() {
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        inicijalizujPolja();
        setTitle("Kreiraj kupca");
        setResizable(false);
        setLocationRelativeTo(null);
        Mesto mestoCreate = (Mesto) comboBoxMesto.getSelectedItem();
        kupacCreate = new Kupac(-1, -1, "+381", "@", mestoCreate, "", "", "", TipKupca.PRAVNO_LICE);
        try {
            Controller.getInstance().kreirajKupca(kupacCreate);
            ArrayList<Kupac> lista = Controller.getInstance().ucitajKupceIzBaze();
            for (Kupac k : lista) {
                if (k.equals(kupacCreate)) {
                    kupacCreate.setId(k.getId());
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(KreirajKupcaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Sistem je kreirao kupca.", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                int choice = JOptionPane.showConfirmDialog(
                        KreirajKupcaForma.this,
                        "Da li želite da prekinete kreiranje kupca?",
                        "Potvrda zatvaranja",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE
                );

                if (choice == JOptionPane.YES_OPTION) {
                    if (kupacCreate != null && kupacChange == null) {
                        try {
                            Controller.getInstance().obrisiKupca(kupacCreate);
                        } catch (Exception ex) {
                            Logger.getLogger(KreirajKupcaForma.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    dispose();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPIB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTelefon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comboBoxMesto = new javax.swing.JComboBox<>();
        btnMestoAdd = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        txtNaziv = new javax.swing.JTextField();
        radioFizicko = new javax.swing.JRadioButton();
        radioPravno = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Naziv firme");

        txtIme.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("PIB");

        txtPIB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Telefon");

        txtTelefon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Email");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSave.setBackground(new java.awt.Color(153, 255, 204));
        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSave.setText("Sačuvaj");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(153, 255, 204));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancel.setText("Otkaži");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Mesto");

        comboBoxMesto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnMestoAdd.setBackground(new java.awt.Color(153, 255, 204));
        btnMestoAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMestoAdd.setText("Dodaj mesto");
        btnMestoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMestoAddActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Ime");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Prezime");

        txtPrezime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNaziv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        radioFizicko.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioFizicko.setText("Fizičko lice");
        radioFizicko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFizickoActionPerformed(evt);
            }
        });

        radioPravno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioPravno.setText("Pravno lice");
        radioPravno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPravnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioPravno, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(radioFizicko, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnCancel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSave))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(comboBoxMesto, javax.swing.GroupLayout.Alignment.LEADING, 0, 335, Short.MAX_VALUE))
                                    .addGap(33, 33, 33)
                                    .addComponent(btnMestoAdd)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPIB, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioPravno)
                    .addComponent(radioFizicko))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPIB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(comboBoxMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMestoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        if (kupacCreate != null && kupacChange == null) {
            try {
                Controller.getInstance().obrisiKupca(kupacCreate);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(KreirajKupcaForma.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        TipKupca tip;
        String naziv = "";
        int pib = 0;
        if (radioFizicko.isSelected()) {
            tip = TipKupca.FIZICKO_LICE;
        } else if (radioPravno.isSelected()) {
            tip = TipKupca.PRAVNO_LICE;
        } else {
            JOptionPane.showMessageDialog(this, "Nije označen tip kupca!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtEmail.getText().isEmpty() || txtIme.getText().isEmpty() || txtTelefon.getText().isEmpty() || txtPrezime.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate popuniti sva polja!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (tip == TipKupca.PRAVNO_LICE) {
            if (txtPIB.getText().isEmpty() || txtNaziv.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Morate popuniti sva polja!", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (Validator.isValidNumber(txtPIB.getText())) {
                try {
                    pib = Integer.parseInt(txtPIB.getText());
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "PIB je prevelik broj!", "Greška", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if (pib < 10000000 || pib > 99999999) {
                    JOptionPane.showMessageDialog(this, "Loš format PIB-a!", "Greška", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } else {
                JOptionPane.showMessageDialog(this, "PIB ne sme da sadrži karaktere!", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            naziv = txtNaziv.getText();
        }

        boolean emailVazeci = validateEmail(txtEmail.getText());
        boolean telefonVazeci = validateTel(txtTelefon.getText());

        if (!emailVazeci) {
            JOptionPane.showMessageDialog(this, "Loš format email-a!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!telefonVazeci) {
            JOptionPane.showMessageDialog(this, "Loš format telefona!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!Validator.isValidName(txtIme.getText()) || !Validator.isValidName(txtPrezime.getText())) {
            JOptionPane.showMessageDialog(this, "Ime i prezime moraju imati samo slova!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String email = txtEmail.getText();
        String telefon = txtTelefon.getText();
        Mesto mesto = (Mesto) comboBoxMesto.getSelectedItem();
        String ime = txtIme.getText();
        String prezime = txtPrezime.getText();

        if (kupacChange == null && kupacCreate != null) {
            try {
                // throw new RuntimeException("Simulacija greške");
                if (tip == TipKupca.PRAVNO_LICE) {
                    kupacCreate.setEmail(email);
                    kupacCreate.setMesto(mesto);
                    kupacCreate.setNaziv(naziv);
                    kupacCreate.setPib(pib);
                    kupacCreate.setTelefon(telefon);
                    kupacCreate.setIme(ime);
                    kupacCreate.setPrezime(prezime);
                    kupacCreate.setTip(TipKupca.valueOf(tip.name()));
                    try {
                        listaKupaca = Controller.getInstance().ucitajKupceIzBaze();
                    } catch (Exception ex) {
                        Logger.getLogger(KreirajKupcaForma.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    for (Kupac k : listaKupaca) {
                        if (k.equals(kupacCreate)) {
                            if (kupacCreate.getId() == k.getId()) {
                                break;
                            } else {
                                JOptionPane.showMessageDialog(this, "Kupac već postoji u bazi.", "Greška", JOptionPane.ERROR_MESSAGE);
                                return;
                            }
                        }
                    }
                    Controller.getInstance().promeniKupca(kupacCreate);
                } else {
                    kupacCreate.setEmail(email);
                    kupacCreate.setMesto(mesto);
                    kupacCreate.setNaziv("");
                    kupacCreate.setPib(-1);
                    kupacCreate.setTelefon(telefon);
                    kupacCreate.setIme(ime);
                    kupacCreate.setPrezime(prezime);
                    kupacCreate.setTip(TipKupca.valueOf(tip.name()));
                    try {
                        listaKupaca = Controller.getInstance().ucitajKupceIzBaze();
                    } catch (Exception ex) {
                        Logger.getLogger(KreirajKupcaForma.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    for (Kupac k : listaKupaca) {
                        if (k.equals(kupacCreate)) {
                            if (kupacCreate.getId() == k.getId()) {
                                break;
                            } else {
                                JOptionPane.showMessageDialog(this, "Kupac već postoji u bazi.", "Greška", JOptionPane.ERROR_MESSAGE);
                                return;
                            }
                        }
                    }
                    Controller.getInstance().promeniKupca(kupacCreate);
                }
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio kupca.", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem nije uspeo da zapamti kupca.", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } else {
            try {
               // throw new RuntimeException("Simulacija greške");
                if (tip == TipKupca.PRAVNO_LICE) {
                    kupacChange.setEmail(email);
                    kupacChange.setMesto((Mesto) comboBoxMesto.getSelectedItem());
                    kupacChange.setNaziv(naziv);
                    kupacChange.setPib(pib);
                    kupacChange.setTelefon(telefon);
                    kupacChange.setIme(ime);
                    kupacChange.setPrezime(prezime);
                    kupacChange.setTip(TipKupca.valueOf(tip.name()));
                    try {
                        listaKupaca = Controller.getInstance().ucitajKupceIzBaze();
                    } catch (Exception ex) {
                        Logger.getLogger(KreirajKupcaForma.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    for (Kupac k : listaKupaca) {
                        if (k.equals(kupacChange)) {
                            if (kupacChange.getId() == k.getId()) {
                                break;
                            } else {
                                JOptionPane.showMessageDialog(this, "Kupac već postoji u bazi.", "Greška", JOptionPane.ERROR_MESSAGE);
                                return;
                            }
                        }
                    }
                    Controller.getInstance().promeniKupca(kupacChange);
                } else {
                    kupacChange.setEmail(email);
                    kupacChange.setMesto((Mesto) comboBoxMesto.getSelectedItem());
                    kupacChange.setNaziv("");
                    kupacChange.setPib(-1);
                    kupacChange.setTelefon(telefon);
                    kupacChange.setIme(ime);
                    kupacChange.setPrezime(prezime);
                    kupacChange.setTip(TipKupca.valueOf(tip.name()));
                    try {
                        listaKupaca = Controller.getInstance().ucitajKupceIzBaze();
                    } catch (Exception ex) {
                        Logger.getLogger(KreirajKupcaForma.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    for (Kupac k : listaKupaca) {
                        if (k.equals(kupacChange)) {
                            if (kupacChange.getId() == k.getId()) {
                                break;
                            } else {
                                JOptionPane.showMessageDialog(this, "Kupac već postoji u bazi.", "Greška", JOptionPane.ERROR_MESSAGE);
                                return;
                            }
                        }
                    }
                    Controller.getInstance().promeniKupca(kupacChange);
                }
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio kupca.", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
                pkf.getTblKupci().setModel(new TableModelKupac());
                TableColumn mestoColumn = pkf.getTblKupci().getColumnModel().getColumn(5);
                mestoColumn.setPreferredWidth(200);
                mestoColumn.setMinWidth(150);
                mestoColumn.setMaxWidth(230);
                TableColumn idColumn = pkf.getTblKupci().getColumnModel().getColumn(0);
                idColumn.setPreferredWidth(30);
                idColumn.setMinWidth(20);
                idColumn.setMaxWidth(40);
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem nije uspeo da zapamti kupca.", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnMestoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMestoAddActionPerformed
        try {
            // TODO add your handling code here:
            boolean dodaj = true;
            KreirajMestoForma kmf = new KreirajMestoForma(this, dodaj);
            kmf.setVisible(true);
            boolean uspeh = kmf.isUspeh();
            if (uspeh == true) {

            }
        } catch (Exception ex) {
            Logger.getLogger(KreirajKupcaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMestoAddActionPerformed

    private void radioFizickoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFizickoActionPerformed
        // TODO add your handling code here:
        if (radioFizicko.isSelected()) {
            jLabel1.setVisible(false);
            jLabel2.setVisible(false);
            txtNaziv.setVisible(false);
            txtPIB.setVisible(false);
            radioPravno.setSelected(false);
        } else {
            jLabel1.setVisible(true);
            jLabel2.setVisible(true);
            txtNaziv.setVisible(true);
            txtPIB.setVisible(true);
            radioPravno.setSelected(true);
        }
    }//GEN-LAST:event_radioFizickoActionPerformed

    private void radioPravnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPravnoActionPerformed
        // TODO add your handling code here:
        if (radioPravno.isSelected()) {
            jLabel1.setVisible(true);
            jLabel2.setVisible(true);
            txtNaziv.setVisible(true);
            txtPIB.setVisible(true);
            radioFizicko.setSelected(false);
        } else {
            jLabel1.setVisible(false);
            jLabel2.setVisible(false);
            txtNaziv.setVisible(false);
            txtPIB.setVisible(false);
            radioFizicko.setSelected(true);
        }
    }//GEN-LAST:event_radioPravnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JToggleButton btnMestoAdd;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<domain.Mesto> comboBoxMesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton radioFizicko;
    private javax.swing.JRadioButton radioPravno;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtPIB;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables

    private void popuniIzmenuKupac(Kupac kupac) {
        if (kupac.getTip() == TipKupca.FIZICKO_LICE) {
            radioFizicko.setSelected(true);
            radioPravno.setSelected(false);
            txtNaziv.setVisible(false);
            txtPIB.setVisible(false);
            jLabel1.setVisible(false);
            jLabel2.setVisible(false);
        }
        if (kupac.getTip() == TipKupca.PRAVNO_LICE) {
            radioPravno.setSelected(true);
            radioFizicko.setSelected(false);
            txtPIB.setText(kupac.getPib() + "");
            txtNaziv.setText(kupac.getNaziv());
        }
        txtIme.setText(kupac.getIme());
        txtPrezime.setText(kupac.getPrezime());
        txtEmail.setText(kupac.getEmail());
        txtTelefon.setText(kupac.getTelefon());
        comboBoxMesto.setSelectedItem(kupac.getMesto());
    }

    private void inicijalizujPolja() {
        radioPravno.setSelected(true);
        try {
            List<Mesto> mesto = Controller.getInstance().ucitajMestaIzBaze();
            mesto.sort(Comparator.comparing(Mesto::getGrad, String.CASE_INSENSITIVE_ORDER));
            for (Mesto m : mesto) {
                comboBoxMesto.addItem(m);
            }
        } catch (Exception ex) {
            Logger.getLogger(KreirajKupcaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean validateEmail(String text) {
        return text.matches("^[a-zA-Z0-9.]+@[a-zA-Z0-9]+\\.[a-zA-Z]{2,}$");
    }

    private boolean validateTel(String text) {
        return text.matches("^\\+381\\d{7,9}$");
    }

}
