/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controller;
import domain.Aranzman;
import domain.PoreskaStopa;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import tableModel.TableModelAranzman;
import validator.Validator;

/**
 *
 * @author Saki
 */
public class KreirajAranzmanForma extends javax.swing.JFrame {

    private Aranzman aranzmanChange;
    private Aranzman aranzmanCreate;
    private UpravljajAranzmanimaForma uaf;
    private ArrayList<Aranzman> listaAranzmana;

    /**
     * Creates new form KreirajAranzmanForma
     */
    public KreirajAranzmanForma() {
        initComponents();
        setTitle("Kreiraj aranžman");
        setResizable(false);
        setLocationRelativeTo(null);
        popuniCombo();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        PoreskaStopa ps = (PoreskaStopa) comboPoreskaStopa.getSelectedItem();
        aranzmanCreate = new Aranzman(-1, "", "", ps, 0, 0, 0);
        try {
            Controller.getInstance().kreirajAranzman(aranzmanCreate);
            ArrayList<Aranzman> lista = Controller.getInstance().ucitajAranzmaneIzBaze();
            for (Aranzman a : lista) {
                if (a.equals(aranzmanCreate)) {
                    aranzmanCreate.setId(a.getId());
                }
            }
            JOptionPane.showMessageDialog(this, "Sistem je kreirao aranžman.", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(KreirajAranzmanForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                int choice = JOptionPane.showConfirmDialog(
                        KreirajAranzmanForma.this,
                        "Da li želite da prekinete kreiranje aranžmana?",
                        "Potvrda zatvaranja",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE
                );

                if (choice == JOptionPane.YES_OPTION) {
                    if (aranzmanCreate != null && aranzmanChange == null) {
                        try {
                            Controller.getInstance().obrisiAranzman(aranzmanCreate);
                        } catch (Exception ex) {
                            Logger.getLogger(KreirajAranzmanForma.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    dispose();
                }
            }
        });
    }

    public KreirajAranzmanForma(JFrame parent, Aranzman a) {
        initComponents();
        this.aranzmanChange = a;
        setTitle("Promeni aranžman");
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        popuniCombo();
        if (a != null) {
            aranzmanChange = a;
            uaf = (UpravljajAranzmanimaForma) parent;
            popuniPolja();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtNaziv = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comboPoreskaStopa = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOpis = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtCenaSaPDV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCenaBezPDV = new javax.swing.JTextField();
        lblpopust = new javax.swing.JLabel();
        txtPopust = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCancel.setBackground(new java.awt.Color(153, 255, 204));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancel.setText("Otkaži");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(153, 255, 204));
        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSave.setText("Sačuvaj");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtNaziv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Naziv");

        comboPoreskaStopa.setBackground(new java.awt.Color(153, 255, 204));
        comboPoreskaStopa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboPoreskaStopa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPoreskaStopaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Poreska stopa");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Opis");

        txtOpis.setColumns(20);
        txtOpis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtOpis.setRows(5);
        jScrollPane1.setViewportView(txtOpis);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Cena sa PDV-om");

        txtCenaSaPDV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Cena bez PDV-a");

        txtCenaBezPDV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblpopust.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblpopust.setText("Popust na aranžman");

        txtPopust.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNaziv))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCenaSaPDV, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblpopust, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPopust, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboPoreskaStopa, 0, 1, Short.MAX_VALUE)
                                    .addComponent(txtCenaBezPDV, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))))))
                .addGap(0, 45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCenaSaPDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtCenaBezPDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPopust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpopust)
                    .addComponent(jLabel2)
                    .addComponent(comboPoreskaStopa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if (aranzmanCreate != null && aranzmanChange == null) {
            try {
                Controller.getInstance().obrisiAranzman(aranzmanCreate);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(KreirajAranzmanForma.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (txtNaziv.getText().isEmpty() || txtCenaBezPDV.getText().isEmpty() || txtCenaSaPDV.getText().isEmpty() || txtOpis.getText().isEmpty() || txtPopust.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate popuniti sva polja!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!Validator.isValidName(txtNaziv.getText())) {
            JOptionPane.showMessageDialog(this, "Loš format naziva!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!Validator.isValidNumber(txtCenaBezPDV.getText()) || !Validator.isValidNumber(txtCenaSaPDV.getText())) {
            JOptionPane.showMessageDialog(this, "Loš unos cene aranžmana!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!Validator.isValidNumber(txtPopust.getText())) {
            JOptionPane.showMessageDialog(this, "Loš unos popusta!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (Double.parseDouble(txtPopust.getText()) > 100) {
            JOptionPane.showMessageDialog(this, "Loš unos popusta!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (Double.parseDouble(txtCenaBezPDV.getText()) >= Double.parseDouble(txtCenaSaPDV.getText())) {
            JOptionPane.showMessageDialog(this, "Loš odnos cena!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        PoreskaStopa ps = (PoreskaStopa) comboPoreskaStopa.getSelectedItem();
        double cenaBez = Double.parseDouble(txtCenaBezPDV.getText());
        double cenaSa = Double.parseDouble(txtCenaSaPDV.getText());
        double popust = Double.parseDouble(txtPopust.getText());
        if (aranzmanChange == null) {
            try {
                aranzmanCreate.setNaziv(txtNaziv.getText());
                aranzmanCreate.setOpis(txtOpis.getText());
                aranzmanCreate.setPoreskaStopa(ps);
                aranzmanCreate.setCenaBezPDV(cenaBez);
                aranzmanCreate.setCenaSaPDV(cenaSa);
                aranzmanCreate.setPopust(popust);
                try {
                    listaAranzmana = Controller.getInstance().ucitajAranzmaneIzBaze();
                } catch (Exception ex) {
                    Logger.getLogger(KreirajAranzmanForma.class.getName()).log(Level.SEVERE, null, ex);
                }

                for (Aranzman a : listaAranzmana) {
                    if (a.equals(aranzmanCreate)) {
                        if (aranzmanCreate.getId() == a.getId()) {
                            break;
                        } else {
                            JOptionPane.showMessageDialog(this, "Aranžman već postoji u bazi.", "Greška", JOptionPane.ERROR_MESSAGE);
                            return;
                        }
                    }
                }
                Controller.getInstance().promeniAranzman(aranzmanCreate);
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio aranžman.", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem nije uspeo da zapamti aranžman.", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }

        } else {
            try {
                aranzmanChange.setNaziv(txtNaziv.getText());
                aranzmanChange.setPoreskaStopa(ps);
                aranzmanChange.setCenaSaPDV(cenaSa);
                aranzmanChange.setCenaBezPDV(cenaBez);
                aranzmanChange.setOpis(txtOpis.getText());
                aranzmanChange.setPopust(popust);
                try {
                    listaAranzmana = Controller.getInstance().ucitajAranzmaneIzBaze();
                } catch (Exception ex) {
                    Logger.getLogger(KreirajAranzmanForma.class.getName()).log(Level.SEVERE, null, ex);
                }

                for (Aranzman a : listaAranzmana) {
                    if (a.equals(aranzmanChange)) {
                        if (aranzmanChange.getId() == a.getId()) {
                            break;
                        } else {
                            JOptionPane.showMessageDialog(this, "Aranžman već postoji u bazi.", "Greška", JOptionPane.ERROR_MESSAGE);
                            return;
                        }
                    }
                }
                Controller.getInstance().promeniAranzman(aranzmanChange);
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio aranžman.", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
                uaf.getTblAranzmani().setModel(new TableModelAranzman());
                TableColumn opisColumn = uaf.getTblAranzmani().getColumnModel().getColumn(5);
                opisColumn.setPreferredWidth(300);
                opisColumn.setMinWidth(200);
                opisColumn.setMaxWidth(400);
                TableColumn idColumn = uaf.getTblAranzmani().getColumnModel().getColumn(0);
                idColumn.setPreferredWidth(30);
                idColumn.setMinWidth(20);
                idColumn.setMaxWidth(40);
                TableColumn nazivColumn = uaf.getTblAranzmani().getColumnModel().getColumn(1);
                nazivColumn.setPreferredWidth(130);
                nazivColumn.setMinWidth(100);
                nazivColumn.setMaxWidth(150);
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem nije uspeo da zapamti aranžman.", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void comboPoreskaStopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPoreskaStopaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPoreskaStopaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KreirajAranzmanForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KreirajAranzmanForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KreirajAranzmanForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KreirajAranzmanForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KreirajAranzmanForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<PoreskaStopa> comboPoreskaStopa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblpopust;
    private javax.swing.JTextField txtCenaBezPDV;
    private javax.swing.JTextField txtCenaSaPDV;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextArea txtOpis;
    private javax.swing.JTextField txtPopust;
    // End of variables declaration//GEN-END:variables

    private void popuniCombo() {
        try {
            ArrayList<PoreskaStopa> poreskaStopa = Controller.getInstance().ucitajPoreskeStopeIzBaze();
            for (PoreskaStopa ps : poreskaStopa) {
                comboPoreskaStopa.addItem(ps);
            }
        } catch (Exception ex) {
            Logger.getLogger(KreirajAranzmanForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniPolja() {
        txtNaziv.setText(aranzmanChange.getNaziv());
        txtCenaSaPDV.setText(aranzmanChange.getCenaSaPDV() + "");
        txtCenaBezPDV.setText(aranzmanChange.getCenaBezPDV() + "");
        txtOpis.setText(aranzmanChange.getOpis());
        txtPopust.setText(aranzmanChange.getPopust() + "");
    }

}
