/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controller;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import domain.Cvecar;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import tableModel.TableModelCvecar;

/**
 *
 * @author Saki
 */
public class KreirajCvecaraForma extends javax.swing.JFrame {

    Cvecar cvecar;
    UpravljajCvecarimaForma pcf;
    private boolean validation;
    private ArrayList<Cvecar> novaLista;

    public boolean isValidation() {
        return validation;
    }

    public void setValidation(boolean validation) {
        this.validation = validation;
    }

    /**
     * Creates new form KreirajCvecaraForma
     */
    public KreirajCvecaraForma() {
        initComponents();
        setResizable(false);
        setTitle("Kreiraj cvecara");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        txtId.setVisible(false);
        jLabel5.setVisible(false);
        btnNovaLozinka.setVisible(false);

    }

    public KreirajCvecaraForma(JFrame parent, Cvecar c) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        txtId.setVisible(true);
        jLabel5.setVisible(true);
        setTitle("Promeni cvecara");
        txtId.setEnabled(false);
        jLabel4.setVisible(false);
        txtLozinka.setVisible(false);
        btnNovaLozinka.setVisible(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        if (c != null) {
            cvecar = c;
            pcf = (UpravljajCvecarimaForma) parent;
            popuniIzmenuCvecar(cvecar);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtKorisnickoIme = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLozinka = new javax.swing.JTextField();
        btnNazad = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnNovaLozinka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Ime");

        txtIme.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIme.setText(" ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Prezime");

        txtPrezime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Korisnicko ime");

        txtKorisnickoIme.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Lozinka");

        txtLozinka.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnNazad.setBackground(new java.awt.Color(153, 255, 204));
        btnNazad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNazad.setText("Otkazi");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        btnSacuvaj.setBackground(new java.awt.Color(153, 255, 204));
        btnSacuvaj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("ID");

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        btnNovaLozinka.setBackground(new java.awt.Color(153, 255, 204));
        btnNovaLozinka.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNovaLozinka.setText("Promeni lozinku");
        btnNovaLozinka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaLozinkaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnNazad)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSacuvaj))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtIme, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                        .addComponent(txtPrezime)
                                        .addComponent(txtId, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                    .addComponent(txtLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(txtKorisnickoIme))
                        .addComponent(btnNovaLozinka, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(btnNovaLozinka)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNazad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        // TODO add your handling code here:

        if (txtIme.getText().isEmpty() || txtPrezime.getText().isEmpty() || txtKorisnickoIme.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate popuniti sva polja!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (cvecar==null && txtKorisnickoIme.getText().equals("admin")) {
            JOptionPane.showMessageDialog(this, "Izabrano korisnicko ime je nedostupno", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String ime = txtIme.getText();
        String prezime = txtPrezime.getText();
        String korisnickoIme = txtKorisnickoIme.getText();
        if (cvecar == null) {
            if (txtLozinka.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Morate popuniti sva polja!", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            } else if ((txtLozinka.getText()).length() < 8) {
                JOptionPane.showMessageDialog(this, "Lozinka mora da ima minimum 8 karaktera!", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String lozinka = txtLozinka.getText();
            Cvecar c = new Cvecar(-1, ime, prezime, korisnickoIme, lozinka);
            try {
                Controller.getInstance().dodajCvecara(c);
            } catch (Exception ex) {
                Logger.getLogger(KreirajCvecaraForma.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Cvecar je dodat", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } else {
            try {
                novaLista = Controller.getInstance().ucitajCvecareIzBaze();
            } catch (Exception ex) {
                Logger.getLogger(KreirajCvecaraForma.class.getName()).log(Level.SEVERE, null, ex);
            }
            cvecar = vratiAzuriranogCvecara();//za slucaj da user promeni sifru opet moramo u bazu da bi azurirali user-a
            //a zatim da ga tako azuriranog prosledimo validaciji da bi se proverila nova sifra a ne stara
            if (cvecar != null) {
                ValidationForm vf = new ValidationForm(this, cvecar);
                vf.setVisible(true);
                System.out.println("va:" + validation);
                if (validation == true) {
                    cvecar.setIme(ime);
                    cvecar.setKorisnickoIme(korisnickoIme);
                    cvecar.setPrezime(prezime);
                    try {
                        Controller.getInstance().promeniCvecara(cvecar);
                        JOptionPane.showMessageDialog(this, "Cvecar je promenjen", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
                        pcf.getTblCvecari().setModel(new TableModelCvecar());
                        this.dispose();
                    } catch (Exception ex) {
                        Logger.getLogger(KreirajCvecaraForma.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnNovaLozinkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaLozinkaActionPerformed
        // TODO add your handling code here:

        PromeniLozinkuForma forma = new PromeniLozinkuForma(pcf, true, cvecar);
        forma.setVisible(true);
    }//GEN-LAST:event_btnNovaLozinkaActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnNovaLozinka;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtKorisnickoIme;
    private javax.swing.JTextField txtLozinka;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void popuniIzmenuCvecar(Cvecar cvecar) {
        txtId.setText(cvecar.getId() + "");
        txtIme.setText(cvecar.getIme());
        txtPrezime.setText(cvecar.getPrezime());
        txtKorisnickoIme.setText(cvecar.getKorisnickoIme());
        txtLozinka.setText("");
    }

    private Cvecar vratiAzuriranogCvecara() {

        for (Cvecar c : novaLista) {
            if (c.getKorisnickoIme().equals(cvecar.getKorisnickoIme())
                    && c.getIme().equals(cvecar.getIme()) && c.getPrezime().equals(cvecar.getPrezime())) {
                return c;
            }
        }
        return null;

    }

}
