/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import tableModel.TableModelKupac;
import controller.Controller;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import domain.Kupac;
import domain.Mesto;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Saki
 */
public class KreirajKupcaForma extends javax.swing.JFrame {
    Kupac kupac;
    UpravljajKupcimaForma pkf;
    /**
     * Creates new form KreirajKupcaForma
     */
     public KreirajKupcaForma(JFrame parent,Kupac k) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);
        inicijalizujPolja();
        if(k!=null){
            setTitle("Promeni kupca");
            kupac=k;
            pkf=(UpravljajKupcimaForma) parent;
            popuniIzmenuKupac(kupac);
        }
    }
    public KreirajKupcaForma() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        inicijalizujPolja();
        setTitle("Kreiraj kupca");
        setResizable(false);
        setLocationRelativeTo(null);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPIB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTelefon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comboBoxMesto = new javax.swing.JComboBox<>();
        btnMestoAdd = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Naziv");

        txtNaziv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("PIB");

        txtPIB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Telefon");

        txtTelefon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Email");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSacuvaj.setBackground(new java.awt.Color(153, 255, 204));
        btnSacuvaj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnNazad.setBackground(new java.awt.Color(153, 255, 204));
        btnNazad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNazad.setText("Otkazi");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Mesto");

        comboBoxMesto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnMestoAdd.setBackground(new java.awt.Color(153, 255, 204));
        btnMestoAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMestoAdd.setText("Dodaj mesto");
        btnMestoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMestoAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNaziv)
                                    .addComponent(txtPIB)
                                    .addComponent(txtTelefon)
                                    .addComponent(txtEmail)
                                    .addComponent(comboBoxMesto, 0, 176, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNazad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(btnSacuvaj)
                        .addGap(21, 21, 21))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMestoAdd)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPIB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboBoxMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMestoAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNazad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        // TODO add your handling code here:
        if(txtEmail.getText().isEmpty() || txtNaziv.getText().isEmpty() || txtPIB.getText().isEmpty() || txtTelefon.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Morate popuniti sva polja!","Greska",JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean emailVazeci=validateEmail(txtEmail.getText());
        boolean telefonVazeci=validateTel(txtTelefon.getText());
        
        if(!emailVazeci){
            JOptionPane.showMessageDialog(this, "Los format emaila","Greska",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!telefonVazeci){
           JOptionPane.showMessageDialog(this, "Los format telefona","Greska",JOptionPane.ERROR_MESSAGE);
           return;
        }
        
        int pib=Integer.parseInt(txtPIB.getText());
        String naziv=txtNaziv.getText();
        String email=txtEmail.getText();
        String telefon=txtTelefon.getText();
        Mesto mesto=(Mesto) comboBoxMesto.getSelectedItem();
        
       
        if(kupac==null){
            try {
                Kupac k=new Kupac( -1,pib, telefon, email, mesto, naziv);
                Controller.getInstance().dodajKupca(k);
                JOptionPane.showMessageDialog(this, "Kupac je dodat","Obavestenje",JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(KreirajKupcaForma.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try {
                Kupac k=new Kupac(-1, pib, telefon, email, mesto, naziv);
                Controller.getInstance().izmeniKupca(k);
                JOptionPane.showMessageDialog(this, "Kupac uspesno izmenjen","Obavestenje",JOptionPane.INFORMATION_MESSAGE);
                pkf.getTblKupci().setModel(new TableModelKupac());
                
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(KreirajKupcaForma.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnMestoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMestoAddActionPerformed
        try {
            // TODO add your handling code here:
            boolean dodaj=true;
            KreirajMestoForma kmf=new KreirajMestoForma(dodaj);
            kmf.setVisible(true);
            boolean uspeh= kmf.isUspeh();
            if(uspeh==true){
                try {
                    comboBoxMesto.removeAllItems();
                    List<Mesto> mesto=Controller.getInstance().ucitajMestaIzBaze();
                    for(Mesto m:mesto){
                        comboBoxMesto.addItem(m);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(KreirajKupcaForma.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(KreirajKupcaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMestoAddActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnMestoAdd;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<domain.Mesto> comboBoxMesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtPIB;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables

    private void popuniIzmenuKupac(Kupac kupac) {
        txtNaziv.setText(kupac.getNaziv());
        txtEmail.setText(kupac.getEmail());
        txtPIB.setText(kupac.getPib()+"");
        txtTelefon.setText(kupac.getTelefon());
        comboBoxMesto.setSelectedItem(kupac.getMesto());
    }

    private void inicijalizujPolja() {
        try {
            List<Mesto> mesto=Controller.getInstance().ucitajMestaIzBaze();
            for(Mesto m:mesto){
                comboBoxMesto.addItem(m);
            }
        } catch (Exception ex) {
            Logger.getLogger(KreirajKupcaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean validateEmail(String text) {
        //return text.matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$");
        return text.matches("^[a-zA-z0-9.]+@[a-zA-z0-9]+\\.[a-zA-Z]{2,}$");
    }

    private boolean validateTel(String text) {
        return text.matches("^\\+381\\d{1,10}$");
    }
}
