/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controller;
import domain.Mesto;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import tableModel.TableModelMesto;

/**
 *
 * @author Saki
 */
public class PregledMestaForma extends javax.swing.JFrame {

    private boolean promena = false;
    private ArrayList<Mesto> lista;
    private boolean uspeh = false;

    public boolean isUspeh() {
        return uspeh;
    }

    public void setUspeh(boolean uspeh) {
        this.uspeh = uspeh;
    }

    public JTable getTblMesta() {
        return tblMesta;
    }

    public void setTblMesta(JTable tblMesta) {
        this.tblMesta = tblMesta;
    }

    /**
     * Creates new form PregledMestaForma
     */
    public PregledMestaForma() {
        initComponents();
        setTitle("Mesta");
        setResizable(false);
        setLocationRelativeTo(null);
        try {
            tblMesta.setModel(new TableModelMesto(controller.Controller.getInstance().ucitajMestaIzBaze()));
        } catch (Exception ex) {
            Logger.getLogger(PregledMestaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMesta = new javax.swing.JTable();
        btnDodajMesto = new javax.swing.JButton();
        btnPromeniMesto = new javax.swing.JButton();
        btnObrisiMesto = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblMesta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMesta);

        btnDodajMesto.setText("dodaj");
        btnDodajMesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajMestoActionPerformed(evt);
            }
        });

        btnPromeniMesto.setText("promeni");
        btnPromeniMesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromeniMestoActionPerformed(evt);
            }
        });

        btnObrisiMesto.setText("obrisi");
        btnObrisiMesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiMestoActionPerformed(evt);
            }
        });

        btnCancel.setText("nazad");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPromeniMesto)
                            .addComponent(btnDodajMesto)
                            .addComponent(btnObrisiMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodajMesto)
                        .addGap(63, 63, 63)
                        .addComponent(btnPromeniMesto)
                        .addGap(62, 62, 62)
                        .addComponent(btnObrisiMesto))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDodajMestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajMestoActionPerformed
        try {
            // TODO add your handling code here:
            KreirajMestoForma kmf=new KreirajMestoForma(this);
            kmf.setVisible(true);
                //tblMesta.setModel(new TableModelMesto(controller.Controller.getInstance().ucitajMestaIzBaze()));//msm da ovo nece refresh
        } catch (Exception ex) {
            Logger.getLogger(PregledMestaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_btnDodajMestoActionPerformed

    private void btnObrisiMestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiMestoActionPerformed
        // TODO add your handling code here:
        try {
            int selektovanRed =  tblMesta.getSelectedRow();
            if (selektovanRed == -1) {
                JOptionPane.showMessageDialog(this, "Nista nije selektovano", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Controller.getInstance().obrisiMesto(lista.get(selektovanRed));

            JOptionPane.showMessageDialog(this, "Mesto obrisano", "greska", JOptionPane.INFORMATION_MESSAGE);

            tblMesta.setModel(new TableModelMesto(Controller.getInstance().ucitajMestaIzBaze()));
        } catch (Exception ex) {
            Logger.getLogger(UpravljajCvecarimaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnObrisiMestoActionPerformed

    private void btnPromeniMestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromeniMestoActionPerformed
        // TODO add your handling code here:
         int selektovanRed=tblMesta.getSelectedRow();
        if(selektovanRed==-1){
            JOptionPane.showMessageDialog(this, "Nista nije selektovano","greska",JOptionPane.ERROR_MESSAGE);
            return;
        }
        Mesto m=lista.get(selektovanRed);
        KreirajMestoForma mf=new KreirajMestoForma(this, m);
        mf.setVisible(true);
        try {
            tblMesta.setModel(new TableModelMesto(Controller.getInstance().ucitajMestaIzBaze()));
        } catch (Exception ex) {
            Logger.getLogger(UpravljajCvecarimaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPromeniMestoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PregledMestaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PregledMestaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PregledMestaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PregledMestaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PregledMestaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDodajMesto;
    private javax.swing.JButton btnObrisiMesto;
    private javax.swing.JButton btnPromeniMesto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMesta;
    // End of variables declaration//GEN-END:variables
}
