/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.Controller;
import domain.Cvecar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.Document;
import validator.PasswordHash;
import validator.Validator;

/**
 *
 * @author Saki
 */
public class PromeniLozinkuForma extends javax.swing.JDialog {

    private Cvecar cvecar;

    /**
     * Creates new form PromeniLozinkuForma
     */
    public PromeniLozinkuForma(java.awt.Frame parent, boolean modal, Cvecar c) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        cvecar = c;
        txtNovaLozinka.setEnabled(false);
        btnChange.setEnabled(false);
        txtErrorPass.setVisible(false);
        unos();
        setTitle("Promena lozinke");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNewPass = new javax.swing.JLabel();
        btnChange = new javax.swing.JButton();
        txtNovaLozinka = new javax.swing.JTextField();
        lblOldPass = new javax.swing.JLabel();
        txtOldPass = new javax.swing.JPasswordField();
        txtErrorPass = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNewPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNewPass.setText("Nova lozinka");

        btnChange.setBackground(new java.awt.Color(153, 255, 204));
        btnChange.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnChange.setText("Promeni");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        txtNovaLozinka.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblOldPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOldPass.setText("Stara lozinka");

        txtOldPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtErrorPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtErrorPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtErrorPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNewPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOldPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtOldPass, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(txtErrorPass)
                    .addComponent(txtNovaLozinka))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChange)
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOldPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtErrorPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNovaLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewPass))
                .addGap(18, 18, 18)
                .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        try {
            // TODO add your handling code here:
            String nova = txtNovaLozinka.getText();
            if (Validator.isValidPassword(nova) == false) {
                JOptionPane.showMessageDialog(this, "Lozinka mora da ima minimum 8 karaktera!", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String hashed = PasswordHash.hashPassword(nova);
            System.out.println("hashed nova:" + hashed);
            cvecar.setLozinka(hashed);
            Controller.getInstance().promeniCvecara(cvecar);
            JOptionPane.showMessageDialog(this, "Lozinka uspešno promenjena!", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();

        } catch (Exception ex) {
            Logger.getLogger(PromeniLozinkuForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnChangeActionPerformed

    private void txtErrorPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtErrorPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtErrorPassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JLabel lblNewPass;
    private javax.swing.JLabel lblOldPass;
    private javax.swing.JTextField txtErrorPass;
    private javax.swing.JTextField txtNovaLozinka;
    private javax.swing.JPasswordField txtOldPass;
    // End of variables declaration//GEN-END:variables

    private void unos() {
        MyDocumentListener listener = new MyDocumentListener();
        txtOldPass.getDocument().addDocumentListener(listener);
    }

    public class MyDocumentListener implements DocumentListener {

        @Override
        public void insertUpdate(DocumentEvent e) {
            validate(e);
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            validate(e);
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            validate(e);
        }

        private void validate(DocumentEvent e) {
            Document source = e.getDocument();

            if (source == txtOldPass.getDocument()) {
                String pass = String.valueOf(txtOldPass.getPassword());
                String hashed = PasswordHash.hashPassword(pass);
                System.out.println("hashed promeni:" + hashed);
                if (hashed.equals(cvecar.getLozinka())) {
                    txtErrorPass.setText("");
                    txtErrorPass.setVisible(false);
                    txtNovaLozinka.setEnabled(true);
                    btnChange.setEnabled(true);

                } else {
                    txtErrorPass.setVisible(true);
                    txtErrorPass.setText("Pogrešna lozinka!");
                }
            }
            txtErrorPass.getParent().revalidate();
        }

    }
}
