/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import tableModel.TableModelOtpremnica;
import controller.Controller;
import domain.Cvecar;
import domain.Kupac;
import domain.Otpremnica;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Saki
 */
public class UpravljajOtpremnicamaForma extends javax.swing.JFrame {

    public JTable getTblOtp() {
        return tblOtp;
    }

    public void setTblOtp(JTable tblOtp) {
        this.tblOtp = tblOtp;
    }

    /**
     * Creates new form PromeniForma
     */
    public UpravljajOtpremnicamaForma() {
        try {
            initComponents();
            promena();
            setTitle("Upravljaj otpremnicama");
            setResizable(false);
            setLocationRelativeTo(null);
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            btnSearch.setVisible(false);
            comboCvecar.setVisible(false);
            comboDatum.setVisible(false);
            comboKupac.setVisible(false);
            lblcvecar.setVisible(false);
            lblkupac.setVisible(false);
            datum.setVisible(false);
            TableModelOtpremnica tmodel = new TableModelOtpremnica();
            tblOtp.setModel(tmodel);
        } catch (Exception ex) {
            Logger.getLogger(UpravljajOtpremnicamaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public UpravljajOtpremnicamaForma(boolean pretraga) {
        try {
            initComponents();
            popuniCombo();
            setTitle("Pretraži otpremnicu");
            btnChange.setVisible(false);
            btnDelete.setVisible(false);
            setResizable(false);
            setLocationRelativeTo(null);
            TableModelOtpremnica tmodel = new TableModelOtpremnica();
            tblOtp.setModel(tmodel);
        } catch (Exception ex) {
            Logger.getLogger(UpravljajOtpremnicamaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOtp = new javax.swing.JTable();
        btnChange = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        datum = new javax.swing.JLabel();
        lblcvecar = new javax.swing.JLabel();
        lblkupac = new javax.swing.JLabel();
        comboKupac = new javax.swing.JComboBox<>();
        comboCvecar = new javax.swing.JComboBox<>();
        comboDatum = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblOtp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblOtp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblOtp);

        btnChange.setBackground(new java.awt.Color(153, 255, 204));
        btnChange.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnChange.setText(" Promeni");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 255, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Otkaži");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(153, 255, 204));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDelete.setText("Obriši");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(153, 255, 204));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearch.setText("Pretraži");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        datum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        datum.setText("Datum izdavanja");

        lblcvecar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblcvecar.setText("Cvećar");

        lblkupac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblkupac.setText("Kupac");

        comboKupac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboKupac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboKupacActionPerformed(evt);
            }
        });

        comboCvecar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        comboDatum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(datum)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(comboCvecar, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboKupac, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(lblcvecar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblkupac, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblkupac)
                            .addComponent(lblcvecar)
                            .addComponent(datum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboCvecar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboKupac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        try {
            int selektovanRed = tblOtp.getSelectedRow();
            if (selektovanRed == -1) {
                JOptionPane.showMessageDialog(this, "Ništa nije označeno!", "Greška", JOptionPane.ERROR_MESSAGE);
            } else {

                try {
                    //throw new RuntimeException("Simulacija greske");
                   TableModelOtpremnica model = (TableModelOtpremnica) tblOtp.getModel();
                    Otpremnica otpremnica = model.getOtpremnica(selektovanRed);
                    JOptionPane.showMessageDialog(this, "Sistem je našao otpremnicu", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);                  
                    KreirajOtpremnicuForma kof = new KreirajOtpremnicuForma(this, otpremnica);
                    kof.setVisible(true);
                    TableModelOtpremnica tmodel = new TableModelOtpremnica();
                    tblOtp.setModel(tmodel);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Sistem nije uspeo da nađe otpremnicu!", "Greška", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(UpravljajOtpremnicamaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            int selektovanRed = tblOtp.getSelectedRow();
            if (selektovanRed == -1) {
                JOptionPane.showMessageDialog(this, "Ništa nije označeno!", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            TableModelOtpremnica model = (TableModelOtpremnica) tblOtp.getModel();
            Otpremnica zaBrisanje = model.getOtpremnica(selektovanRed);
            try {
                //throw new RuntimeException("Simulacija greske");
                Controller.getInstance().obrisiOtpremnicu(zaBrisanje);
            } catch (SQLIntegrityConstraintViolationException ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da obriše otpremnicu!", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(this, "Sistem je uspešno obrisao otpremnicu", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);

            TableModelOtpremnica tmodel = new TableModelOtpremnica();
            tblOtp.setModel(tmodel);
        } catch (Exception ex) {
            Logger.getLogger(UpravljajCvecarimaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            // TODO add your handling code here:
            Object obj = (Object) comboDatum.getSelectedItem();
            Date datum = new Date();
            if (obj.equals("Bilo koji")) {
                datum = null;
            } else {
                datum = (Date) comboDatum.getSelectedItem();
            }
            Cvecar cvecar = (Cvecar) comboCvecar.getSelectedItem();
            Kupac kupac = (Kupac) comboKupac.getSelectedItem();
            btnChange.setVisible(true);
            btnDelete.setVisible(true);
            Otpremnica filter = new Otpremnica();
            if (cvecar.getIme().equals("Bilo") && cvecar.getPrezime().equals("koji")) {
                cvecar = null;
            }
            if (kupac.getNaziv().equals("Bilo koji")) {
                kupac = null;
            }
            filter.setDatumIzdavanja(datum);
            filter.setCvecar(cvecar);
            filter.setKupac(kupac);
            ArrayList<Otpremnica> filtriraneOtpremnice = Controller.getInstance().pretraziOtpremnice(filter);
            TableModelOtpremnica model = new TableModelOtpremnica(filtriraneOtpremnice);
            tblOtp.setModel(model);
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Sistem nije uspeo da nađe otpremnice po zadatim kriterijumima!", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                JOptionPane.showMessageDialog(this, "Sistem je našao otpremnice po zadatim kriterijumima", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        } catch (Exception ex) {
            Logger.getLogger(UpravljajOtpremnicamaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void comboKupacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboKupacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboKupacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpravljajOtpremnicamaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpravljajOtpremnicamaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpravljajOtpremnicamaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpravljajOtpremnicamaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<Cvecar> comboCvecar;
    private javax.swing.JComboBox<Object> comboDatum;
    private javax.swing.JComboBox<Kupac> comboKupac;
    private javax.swing.JLabel datum;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcvecar;
    private javax.swing.JLabel lblkupac;
    private javax.swing.JTable tblOtp;
    // End of variables declaration//GEN-END:variables

    private void promena() {
        btnSearch.setVisible(false);
        lblcvecar.setVisible(false);
        lblkupac.setVisible(false);
        datum.setVisible(false);
        comboCvecar.setVisible(false);
        comboDatum.setVisible(false);
        comboKupac.setVisible(false);
    }

    private void popuniCombo() throws Exception {

        comboKupac.removeAllItems();
        Kupac defaultKupac = new Kupac();
        defaultKupac.setNaziv("Bilo koji");
        comboKupac.addItem(defaultKupac);
        ArrayList<Kupac> kupci = Controller.getInstance().ucitajKupceIzBaze();
        for (Kupac k : kupci) {
            comboKupac.addItem(k);
        }
        comboCvecar.removeAllItems();
        Cvecar defaultCvecar = new Cvecar();
        defaultCvecar.setIme("Bilo");
        defaultCvecar.setPrezime("koji");
        comboCvecar.addItem(defaultCvecar);
        ArrayList<Cvecar> cvecari = Controller.getInstance().ucitajCvecareIzBaze();
        for (Cvecar c : cvecari) {
            comboCvecar.addItem(c);
        }
        comboDatum.removeAllItems();
        comboDatum.addItem("Bilo koji");
        ArrayList<Otpremnica> otpremnice = Controller.getInstance().ucitajOtpremniceIzBaze();
        for (Otpremnica o : otpremnice) {
            comboDatum.addItem(o.getDatumIzdavanja());
        }
    }
}
