/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controller;
import domain.Cvecar;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import tableModel.TableModelCvecar;

/**
 *
 * @author Saki
 */
public class UpravljajCvecarimaForma extends javax.swing.JFrame {

    private ArrayList<Cvecar> lista;
    private TableModelCvecar tma;
    private Cvecar ulogovani;

    public JTable getTblCvecari() {
        return tblCvecari;
    }

    public void setTblCvecari(JTable tblCvecari) {
        this.tblCvecari = tblCvecari;
    }

    /**
     * Creates new form PromeniCvecaraForma
     */
    public UpravljajCvecarimaForma(Cvecar ulogovani) {
        try {
            initComponents();
            this.ulogovani = ulogovani;
            adminCheck();
            setTitle("Upravljaj cvećarima");
            tma = new TableModelCvecar();
            tblCvecari.setModel(tma);
            setResizable(false);
            setLocationRelativeTo(null);
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            btnChange.setEnabled(false);
            TableColumn idColumn = tblCvecari.getColumnModel().getColumn(0);
            idColumn.setPreferredWidth(30);
            idColumn.setMinWidth(20);
            idColumn.setMaxWidth(40);
        } catch (Exception ex) {
            Logger.getLogger(UpravljajCvecarimaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCvecari = new javax.swing.JTable();
        btnChange = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCvecari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblCvecari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCvecari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCvecariMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCvecari);

        btnChange.setBackground(new java.awt.Color(153, 255, 204));
        btnChange.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnChange.setText("Promeni");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(153, 255, 204));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDelete.setText("Obriši");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(153, 255, 204));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancel.setText("Otkaži");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
        int selektovanRed = tblCvecari.getSelectedRow();
        if (selektovanRed == -1) {
            JOptionPane.showMessageDialog(this, "Ništa nije označeno!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        TableModelCvecar tmm = (TableModelCvecar) tblCvecari.getModel();
        Cvecar c = tmm.getCvecar(selektovanRed);
        JOptionPane.showMessageDialog(this, "Sistem je našao cvećara.", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
        KreirajCvecaraForma kf = new KreirajCvecaraForma(this, c);
        kf.setVisible(true);
        TableColumn idColumn = tblCvecari.getColumnModel().getColumn(0);
        idColumn.setPreferredWidth(30);
        idColumn.setMinWidth(20);
        idColumn.setMaxWidth(40);
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tblCvecariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCvecariMouseClicked
        // TODO add your handling code here:
        int selektovanRed = tblCvecari.getSelectedRow();
        if (selektovanRed != -1) {
            btnChange.setEnabled(true);
            if (btnDelete.isVisible() == true) {
                btnDelete.setEnabled(true);
            }
        }
    }//GEN-LAST:event_tblCvecariMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            int selektovanRed = tblCvecari.getSelectedRow();
            if (selektovanRed == -1) {
                JOptionPane.showMessageDialog(this, "Ništa nije označeno!", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }

            TableModelCvecar tmm = (TableModelCvecar) tblCvecari.getModel();
            Cvecar cvecarDelete = tmm.getCvecar(selektovanRed);
            try {
                Controller.getInstance().obrisiCvecara(cvecarDelete);
            } catch (SQLIntegrityConstraintViolationException ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da obriše cvećara.", "Greška", JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(this, "Sistem je uspešno obrisao cvećara.", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);

            tmm.refresh();
            tblCvecari.setModel(tmm);
            TableColumn idColumn = tblCvecari.getColumnModel().getColumn(0);
            idColumn.setPreferredWidth(30);
            idColumn.setMinWidth(20);
            idColumn.setMaxWidth(40);
        } catch (Exception ex) {
            Logger.getLogger(UpravljajCvecarimaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnDelete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCvecari;
    // End of variables declaration//GEN-END:variables

    private void adminCheck() {
        if (!ulogovani.getKorisnickoIme().equals("admin")) {
            btnDelete.setVisible(false);
        } else {
            btnDelete.setVisible(true);
            btnDelete.setEnabled(false);
        }
    }
}
